...
widgets = {
    ...
    'doctor': autocomplete.ModelSelect2(url='appointments:doctor_autocomplete', attrs={'data-placeholder': 'Select Doctor','class':'form-control','data-minimum-input-length': 0},),
    ...
}
...
